export const STORAGE_KEYS = {
  ACTIVE_MODE: "replay-active-mode",
  AI_MODEL: "replay-ai-model",
  INSTRUMENT: "replay-instrument",
  BPM: "replay-bpm",
  TIME_SIGNATURE: "replay-time-signature",
  METRONOME_BEAT_UNIT: "replay-metronome-beat-unit",
  METRONOME_FEEL: "replay-metronome-feel",
  COMPOSE_HISTORY: "replay-compose-history",
  IMPROV_HISTORY: "replay-improv-history",
  PLAY_HISTORY: "replay-play-history",
  METRONOME_VOLUME: "replay-metronome-volume",
  METRONOME_SOUND: "replay-metronome-sound",
  AUTOREPLY: "replay-autoreply",
  LEARN_DIFFICULTY: "replay-learn-difficulty",
  LANGUAGE: "replay-language",
} as const;
