-- Add new columns to lesson_runs for the Teacher/Lesson Teacher architecture

-- Version reference for curriculum snapshot
ALTER TABLE lesson_runs ADD COLUMN IF NOT EXISTS version_id uuid REFERENCES curriculum_versions(id);

-- Compiled lesson brief (stored once at lesson start, reused for all turns)
ALTER TABLE lesson_runs ADD COLUMN IF NOT EXISTS lesson_brief jsonb;

-- Demo sequence generated by Coach INTRO
ALTER TABLE lesson_runs ADD COLUMN IF NOT EXISTS demo_sequence jsonb;

-- Metronome context for timing analysis (t0, bpm, meter, feel, countInBars)
ALTER TABLE lesson_runs ADD COLUMN IF NOT EXISTS metronome_context jsonb;

-- User's last recorded attempt
ALTER TABLE lesson_runs ADD COLUMN IF NOT EXISTS user_recording jsonb;

-- Lesson state machine (turn, passStreak, failStreak, lastDecision, phase)
ALTER TABLE lesson_runs ADD COLUMN IF NOT EXISTS state jsonb DEFAULT '{"turn": 0, "passStreak": 0, "failStreak": 0, "lastDecision": null, "phase": "intro"}'::jsonb;

-- Grader diagnosis tags
ALTER TABLE lesson_runs ADD COLUMN IF NOT EXISTS diagnosis jsonb;

-- AI feedback text from Coach
ALTER TABLE lesson_runs ADD COLUMN IF NOT EXISTS ai_feedback text;

-- Index for faster lookups by version
CREATE INDEX IF NOT EXISTS idx_lesson_runs_version_id ON lesson_runs(version_id);